apiVersion: v1
kind: Secret
metadata:
  name: datactive-secret
type: Opaque
stringData:
  DefaultConnection: "Host=PLACEHOLDER_HOST;Port=PLACEHOLDER_PORT;Database=PLACEHOLDER_DB;Username=PLACEHOLDER_USER;Password=PLACEHOLDER_PASSWORD;Pooling=true;$$5"
