apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - datactive-config.yaml
  - datactive-secret.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: datactive-web
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: datactive-gitops
