apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: build-build-20260806-134049

resources:
  - "../../base"

images:
  - name: harbor.datactive.net/datateam/datactive.web
    newTag: "BUILD-20260806-134049"

configMapGenerator:
  - name: datactive-config
    behavior: merge
    literals:
      - DQLSchema=schema_k1_5
      - CustomerMetadataSchema=schema_k1_5.
      - ORACLEDataSchema=schema_k1_5.
