apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: build-20260810-build

resources:
  - "../../base"

images:
  - name: datactive-registry:5000/datateam/datactive.web
    newTag: "BUILD-20260810-131654"

configMapGenerator:
  - name: datactive-config
    behavior: merge
    literals:
      - DQLSchema=schema_dev
      - CustomerMetadataSchema=schema_dev.
      - ORACLEDataSchema=schema_dev.
