apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: build-20260806-build

resources:
  - "../../base"

images:
  - name: harbor.datactive.net/datateam/datactive.web
    newTag: "BUILD-20260806-135906"

configMapGenerator:
  - name: datactive-config
    behavior: merge
    literals:
      - DQLSchema=schema_final_test
      - CustomerMetadataSchema=schema_final_test.
      - ORACLEDataSchema=schema_final_test.
