apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: build-20260806-build

resources:
  - "../../base"

images:
  - name: harbor.datactive.net/datateam/datactive.web
    newTag: "BUILD-20260806-140816"

configMapGenerator:
  - name: datactive-config
    behavior: merge
    literals:
      - DQLSchema=schema_new_commit
      - CustomerMetadataSchema=schema_new_commit.
      - ORACLEDataSchema=schema_new_commit.
