name: Build

on:
  workflow_dispatch:
    inputs:
      branch_web:
        description: "Web uygulaması branch adı"
        required: true
        type: string
      branch_server:
        description: "Server uygulaması branch adı"
        required: true
        type: string
      schema:
        description: "DB schema adı"
        required: true
        type: string
      tag:
        description: "Build tag'i (Tag Formatı'na uygun)"
        required: true
        type: string

jobs:
  build:
    runs-on: arc-runner-set
    container:
      image: datactive-registry:5000/datateam/datactive-build:latest
      options: --privileged
    steps:
      - name: Checkout (local action için)
        uses: actions/checkout@v4

      - name: Inputs
        run: |
          echo "branch_web=${{ inputs.branch_web }}"
          echo "branch_server=${{ inputs.branch_server }}"
          echo "schema=${{ inputs.schema }}"
          echo "tag=${{ inputs.tag }}"

      - name: DatActive Build
        uses: ./.github/actions/build-datactive
        with:
          branch_web: ${{ inputs.branch_web }}
          branch_server: ${{ inputs.branch_server }}
          tag: ${{ inputs.tag }}
          token: ${{ secrets.PAT_TOKEN }}
